#-Basic info----------------------------------------------------------------------------------------
name: qcquickie
version: 1.0.0
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: denovo_assembly
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: required
  description: >
    This does de-novo assembly on a sample and then maps the reads back against the denovo assembly
    for variant calling. In the process it gathers metrics on many aspects for the use of QC. This
    generates the same metrics as qcquickie but should yield better contigs and it is recommended
    to use these contigs for downstream analysis.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://stefanocardinale/bifrost-qcquickie:1.0.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  cov_bin_values: [1, 10, 25]
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  adapters_fasta: "/bifrost_resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - qcquickie/contigs.fasta
    - qcquickie/contigs.bin.cov
    - qcquickie/contigs.gff
    - qcquickie/contigs.pileup
    - qcquickie/contigs.sketch
    - qcquickie/contigs.stats
    - qcquickie/contigs.sum.cov
    - qcquickie/contigs.variants
  sample:
    properties:
      denovo_assembly:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
  sample_component:
      summary:
        bin_contigs_at_1x:
        bin_length_at_1x:
        bin_coverage_at_1x:
        bin_contigs_at_10x:
        bin_length_at_10x:
        bin_coverage_at_10x:
        bin_contigs_at_25x:
        bin_length_at_25x:
        bin_coverage_at_25x:
        raw_length_at_1x:
        raw_length_at_10x:
        raw_length_at_25x:
        filtered_reads_num:
        GC:
        N50:
        snp_filter_10x_10%:
        snp_filter_indels:
        snp_filter_deletions:
        raw_total_sequences:
        reads_mapped:
        reads_unmapped:
        insert_size_average:
        insert_size_standard_deviation:
      results:
        qcquickie/contigs_sum_cov: {}
        qcquickie/contigs_bin_cov: {}
        qcquickie/log/setup__filter_reads_with_bbduk_err_log: {}
        qcquickie/quast/report_tsv: {}
        qcquickie/contigs_variants: {}
        assemblatron/contigs_stats: {}
#---------------------------------------------------------------------------------------------------
